name: Drama Robot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Data
        run: |
          echo '{"status": "success"}' > data.json
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json
          git commit -m "Update links" || exit 0
          git push
