name: AI DRAMA ROBOT
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Activate Channels
        run: |
          echo '{"status": "active", "date": "'$(date)'"}' > data.json
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json
          git commit -m "Channels Activated ✅" || exit 0
          git push
